version: '3.4'

services:
  parking-service:
    image: ${DOCKER_REGISTRY-}parking-service
    build:
      context: .
      dockerfile: ParkingService/Dockerfile
    # ports:
    #     - "52436:80"
    # networks:
    #     - cello-network
    depends_on:
        - sql-server
    container_name: parking-service

  payment-service:
    image: ${DOCKER_REGISTRY-}payment-service
    build:
      context: .
      dockerfile: PaymentService/Dockerfile
    # ports:
    #     - "52433:80"
    # networks:
    #     - cello-network
    container_name: payment-service

  transaction-service:
    image: ${DOCKER_REGISTRY-}transaction-service
    build:
      context: .
      dockerfile: TransactionService/Dockerfile
    depends_on:
        - parking-service
        - payment-service
    container_name: transaction-service
 
  sql-server:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=StrongPassword123!
        - MSSQL_PID=Express
        - ConnectionStrings__DefaultConnection=Server=sql-server,1433;Database=Cello;User Id=sa;Password=StrongPassword123!;
    ports:
        - "1433:1433"
    container_name: sql-server
    volumes:
      - sqlserver_data:/var/opt/mssql
volumes:
  sqlserver_data:

