// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaymentService.DbContexts;

#nullable disable

namespace PaymentService.Migrations
{
    [DbContext(typeof(PaymentContext))]
    [Migration("20241015063311_PaymentServiceTables")]
    partial class PaymentServiceTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.35")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PaymentService.DbContexts.Models.ParkingLot", b =>
                {
                    b.Property<int>("ParkingLotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParkingLotId"), 1L, 1);

                    b.Property<double>("MaxTariff")
                        .HasColumnType("float");

                    b.Property<double>("MinTariff")
                        .HasColumnType("float");

                    b.Property<string>("SpecialHoursTariffOverride")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TariffPerAdditionalHour")
                        .HasColumnType("float");

                    b.HasKey("ParkingLotId");

                    b.ToTable("ParkingLots");
                });

            modelBuilder.Entity("PaymentService.DbContexts.Models.TariffPerHour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Hour")
                        .HasColumnType("int");

                    b.Property<int>("ParkingLotId")
                        .HasColumnType("int");

                    b.Property<double>("Tariff")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ParkingLotId");

                    b.ToTable("TariffPerHour");
                });

            modelBuilder.Entity("PaymentService.DbContexts.Models.TariffPerHour", b =>
                {
                    b.HasOne("PaymentService.DbContexts.Models.ParkingLot", "ParkingLot")
                        .WithMany("TariffsPerInitialHours")
                        .HasForeignKey("ParkingLotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParkingLot");
                });

            modelBuilder.Entity("PaymentService.DbContexts.Models.ParkingLot", b =>
                {
                    b.Navigation("TariffsPerInitialHours");
                });
#pragma warning restore 612, 618
        }
    }
}
